{{- $fullName := include "media-common.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $apiv1 := .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}
{{- $apiv1beta1 := .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" -}}
{{- $ingresses := concat (list .Values.ingress) .Values.extraIngresses -}}
{{- range $index, $ingress := $ingresses }}
  {{- if $ingress.enabled -}}
    {{- if $apiv1 -}}
apiVersion: networking.k8s.io/v1
    {{- else if $apiv1beta1 -}}
apiVersion: networking.k8s.io/v1beta1
    {{- else -}}
apiVersion: extensions/v1beta1
    {{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}{{- if ne $index 0 }}{{- printf "-%s" (default $index $ingress.nameSuffix) }}{{- end }}
  labels:
  {{- include "media-common.labels" $ | nindent 4 }}
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $ingress.tls }}
  tls:
    {{- range . }}
    - secretName: {{ .secretName }}
      hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
  rules:
  {{- range $ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if or $apiv1beta1 $apiv1 }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if $apiv1 }}
              service:
                name: {{ $fullName }}
                port:
                  name: http
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
  {{- end }}
---
  {{- end }}
{{- end }}
